// Generated by CoffeeScript 1.10.0
(function() {
  var i, len, potatoCount, potatoInit, potatoUpgrades, type, upgradeInsert, upgradeTypes;

  potatoCount = 0;

  potatoUpgrades = {};

  upgradeTypes = ["farm", "factory", "kappa"];

  for (i = 0, len = upgradeTypes.length; i < len; i++) {
    type = upgradeTypes[i];
    potatoUpgrades[type] = 0;
  }

  potatoInit = function() {
    potatoCount += 1;
    return console.log(potatoCount);
  };

  setInterval(potatoInit, 2000);

  upgradeInsert = function(type) {
    potatoUpgrades[type] = potatoUpgrades[type] += 1;
    return console.log(potatoUpgrades[type]);
  };

  $("#upgradeBtnF").on("click", upgradeInsert("field"));

  $("#upgradeBtnFa").on("click", upgradeInsert("factory"));

  $("#upgradeBtnK").on("click", upgradeInsert("kappa"));

}).call(this);
