// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var buttonValues, displayUpgrade, initUi, uiUpdate;
    initUi = function() {
      return setInterval(uiUpdate, 200);
    };
    displayUpgrade = function() {
      var i, j, ref, results, type;
      $("#resourceDisplay").text("");
      results = [];
      for (i = j = 0, ref = upgradeTypes.length - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        type = upgradeTypes[i];
        if (potatoUpgrades[type] > 0) {
          results.push($("#resourceDisplay").append("<p>" + type + ": " + potatoUpgrades[type] + "</p>"));
        } else {
          results.push(void 0);
        }
      }
      return results;
    };
    buttonValues = function() {
      $("#upgradeBtnF").attr("value", "Build a Farm. Cost: " + (countConvert(upgradeCosts["farm"])));
      $("#upgradeBtnFa").attr("value", "Build a Factory. Cost: " + (countConvert(upgradeCosts["factory"])));
      $("#upgradeBtnK").attr("value", "Build a Kappa. Cost: " + (countConvert(upgradeCosts["kappa"])));
      return $("#upgradeBtnC").attr("value", "Build a Copy machine. Cost: " + (countConvert(upgradeCosts["copy_machine"])));
    };
    $("#upgradeBtnFa").on("click", function() {
      return upgradeInsert("factory", "user");
    });
    $("#upgradeBtnK").on("click", function() {
      return upgradeInsert("kappa", "user");
    });
    $("#upgradeBtnF").on("click", function() {
      return upgradeInsert("farm", "user");
    });
    $("#upgradeBtnC").on("click", function() {
      return upgradeInsert("copy_machine", "user");
    });
    $("#potatoGet").on("click", function() {
      return potatoGet();
    });
    $(":button").on("click", function() {
      return uiUpdate();
    });
    $("#sacrifice1").on("click", function() {
      return sacrifice(1);
    });
    $("#spell1").on("click", function() {
      return spells["golem"].cast();
    });
    uiUpdate = function() {
      $("#label").text("Potatoes: " + (countConvert(potatoCount)));
      $("#ps").text("Potatoes/second: " + (countConvert(modifier)));
      $("#mana").text("mana: " + mana);
      $("#spellmod").text("" + magicMultiplier);
      return displayUpgrade();
    };
    initStuff();
    return initUi();
  });

}).call(this);
